kumuluzee:
  name: mag2020-aws-storage
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8002
    http:
      port: 8002
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
app-properties:
  aws:
    s3:
      access-key: accessKey
      secret-key: secretKey